#!/usr/bin/env ruby
require 'fileutils'

def link(path, link_name)
  path = File.expand_path path
  link_name = File.expand_path link_name

  puts "linking #{link_name}..."

  if File.symlink? link_name
    puts "\tRemoving symlink..."
    FileUtils.rm link_name
  elsif File.exists? link_name
    puts "\tSkipping because a file already exists."
    return
  end

  FileUtils.ln_s(path, link_name)
end

puts "Installing Environments..."
# Dir.glob('./*/setup.sh').each { |f| system("sh #{f}") }

# puts "Bootstrapping Dotfiles..."
link "~/dotfiles/zsh/.zshrc", "~/.zshrc"

puts "done"